theme: jekyll-theme-cayman
title: Welcome to Zheyi Xu's Home Page!

description: 
- Auditor @ Ernst & Young Shanghai
- Member of Chinese Computer Federation (CCF) & Association of Computing Machinery (ACM)
- Part-Time Student of Computer Science @ UoPeople
- Email: luciaxuzheyi@outlook.com   
- Phone: +86 13816121406
- LinkedIn: [https://www.linkedin.cn/incareer/in/zheyixu]
