theme: jekyll-theme-minimal
title: Welcome to Zheyi Xu's Home Page ![profile photo-1](https://github.com/luciaxuzheyi/zheyixu.github.io/blob/gh-pages/profile%20photo-1.jpg)
description: 
- Auditor @ Ernst & Young Shanghai</b></p>
- Member of Chinese Computer Federation (CCF) & Association of Computing Machinery (ACM)</b></p>
- Part-Time Student of Computer Science @ UoPeople
- Email: luciaxuzheyi@outlook.com   
- Phone: +86 13816121406</b></p>
- LinkedIn: [https://www.linkedin.cn/incareer/in/zheyixu]</b></p>
